# Auto-generated by scaffold.py
# utils/logger.py
# Append-only JSONL logger
# Safe for crashes, never read at runtime

import json
import time
from pathlib import Path

LOG_FILE = Path("data/logs.jsonl")

def log_event(event_type: str, payload: dict, debug=True):
    event = {
        "timestamp": time.time(),
        "event_type": event_type,
        "payload": payload
    }

    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(event) + "\n")

        if debug:
            print(f"[LOGGER] Event logged: {event_type}")

    except Exception as e:
        print("[LOGGER ERROR]", e)