# Auto-generated by scaffold.py
# utils/normalizer.py
# Normalize raw speech text for routing
# NO intent logic here

import re

FILLER_WORDS = [
    "please",
    "can you",
    "could you",
    "would you",
    "hey",
    "hi",
    "uh",
    "um",
    "for me"
]

def normalize(text: str, debug=True) -> str:
    if debug:
        print(f"[NORMALIZER] Raw text: '{text}'")

    if not text:
        return ""

    text = text.lower().strip()

    for filler in FILLER_WORDS:
        text = text.replace(filler, "")

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    normalized = text.strip()

    if debug:
        print(f"[NORMALIZER] Normalized text: '{normalized}'")

    return normalized