# Auto-generated by scaffold.py
# utils/validators.py
# Validates intent objects before execution

from jsonschema import validate, ValidationError

INTENT_SCHEMA = {
    "type": "object",
    "required": ["intent_id", "params", "confidence", "source"],
    "properties": {
        "intent_id": {
            "type": "string",
            "enum": [
                "MODE_SWITCH",
                "OPEN_WEBSITE",
                "OPEN_APP",
                "SEARCH_WEB",
                "TEXT_INPUT",
                "TEXT_FORMAT",
                "CODE_GENERATION",
                "KEY_COMMAND",
                "EDIT_ACTION",
                "NAVIGATION",
                "UNKNOWN"
            ]
        },
        "params": {
            "type": "object"
        },
        "confidence": {
            "type": "number",
            "minimum": 0.0,
            "maximum": 1.0
        },
        "source": {
            "type": "string",
            "enum": ["RULES", "AI"]
        }
    }
}

def validate_intent(intent: dict, debug=True) -> bool:
    try:
        validate(instance=intent, schema=INTENT_SCHEMA)

        if debug:
            print("[VALIDATOR] Intent schema valid")

        return True

    except ValidationError as e:
        print("[VALIDATOR ERROR] Schema validation failed:", e)
        return False


def is_confidence_acceptable(intent: dict, min_confidence: float, debug=True) -> bool:
    confidence = intent.get("confidence", 0.0)

    if confidence >= min_confidence:
        if debug:
            print(f"[VALIDATOR] Confidence OK: {confidence}")
        return True

    if debug:
        print(f"[VALIDATOR] Confidence too low: {confidence}")

    return False