# Auto-generated by scaffold.py
# tests/test_rules.py
# Tests rule-based intent routing

from intent.rule_router import route

def test_open_youtube_rule():
    text = "open youtube"
    intent = route(text)

    print("[TEST] open youtube ->", intent)

    assert intent is not None
    assert intent["intent_id"] == "OPEN_WEBSITE"
    assert "youtube" in intent["params"]["url"]


def test_mode_switch_rule():
    text = "command mode"
    intent = route(text)

    print("[TEST] command mode ->", intent)

    assert intent["intent_id"] == "MODE_SWITCH"
    assert intent["params"]["mode"] == "COMMAND"


def test_unknown_rule():
    text = "this should not match"
    intent = route(text)

    print("[TEST] unknown ->", intent)

    assert intent is None