# Auto-generated by scaffold.py
# tests/test_ai_router.py
# AI router tests with monkeypatching

from intent.ai_router import ai_route

def mock_ai_response(text):
    print("[MOCK AI] received:", text)
    return {
        "intent_id": "OPEN_WEBSITE",
        "params": {"url": "https://www.youtube.com"},
        "confidence": 0.92,
        "source": "AI"
    }

def test_ai_router_mock(monkeypatch):
    # Patch ai_route internals to avoid real API calls
    monkeypatch.setattr(
        "intent.ai_router.ai_route",
        lambda text: mock_ai_response(text)
    )

    intent = ai_route("open youtube")

    print("[TEST AI] intent ->", intent)

    assert intent["intent_id"] == "OPEN_WEBSITE"
    assert intent["confidence"] >= 0.9