# Auto-generated by scaffold.py
# tests/test_keyboard.py
# KeyboardBrain execution tests with mocks

from brain.state import State
from brain.keyboard_brain import KeyboardBrain

def test_open_website_execution(monkeypatch):
    # Mock OS action
    def mock_open_website(url):
        print("[MOCK OS] open_website called with:", url)
        assert "youtube" in url

    monkeypatch.setattr(
        "os_actions.os_actions.open_website",
        mock_open_website
    )

    settings = {
        "debug": {"print_execution": True},
        "execution": {"default_mode": "COMMAND"}
    }

    keys = {
        "virtual_keys": {}
    }

    state = State(default_mode="COMMAND", debug=True)
    brain = KeyboardBrain(state, settings, keys)

    intent = {
        "intent_id": "OPEN_WEBSITE",
        "params": {"url": "https://www.youtube.com"}
    }

    brain.execute(intent)

    assert state.last_intent == "OPEN_WEBSITE"