# Auto-generated by scaffold.py
# intent/moderation.py

import re

LEARNABLE = {
    "OPEN_WEBSITE",
    "OPEN_APP",
    "SEARCH_WEB",
    "KEY_COMMAND",
    "MODE_SWITCH"
}

PERSONAL_PATTERNS = [
    r"\bmy\b",
    r"\bme\b",
    r"\bpassword\b",
    r"\bemail\b",
    r"\bphone\b"
]

FILE_PATH_PATTERN = r"[A-Za-z]:\\|/|~"

def is_safe_to_learn(intent: dict, text: str):
    print("[MODERATION] Checking intent:", intent["intent_id"])

    if intent["intent_id"] not in LEARNABLE:
        print("[MODERATION] Intent not learnable")
        return False

    if intent["confidence"] < 0.9:
        print("[MODERATION] Confidence too low")
        return False

    if re.search(FILE_PATH_PATTERN, text):
        print("[MODERATION] File path detected")
        return False

    for pat in PERSONAL_PATTERNS:
        if re.search(pat, text):
            print("[MODERATION] Personal data detected")
            return False

    print("[MODERATION] Intent safe to learn")
    return True