# Auto-generated by scaffold.py
# intent/schema.py
# Canonical intent JSON schema

INTENT_IDS = [
    "MODE_SWITCH",
    "OPEN_WEBSITE",
    "OPEN_APP",
    "SEARCH_WEB",
    "TEXT_INPUT",
    "TEXT_FORMAT",
    "CODE_GENERATION",
    "KEY_COMMAND",
    "EDIT_ACTION",
    "NAVIGATION",
    "UNKNOWN"
]

INTENT_SCHEMA = {
    "type": "object",
    "required": ["intent_id", "params", "confidence", "source"],
    "properties": {
        "intent_id": {
            "type": "string",
            "enum": INTENT_IDS
        },
        "params": {
            "type": "object"
        },
        "confidence": {
            "type": "number",
            "minimum": 0.0,
            "maximum": 1.0
        },
        "source": {
            "type": "string",
            "enum": ["RULES", "AI"]
        }
    }
}