# Auto-generated by scaffold.py
# os_actions/browser.py
# Browser-specific helpers
# Uses keyboard + web only, no direct browser APIs

import webbrowser
from os_actions.keyboard_utils import press_combo

def search_web(query: str, debug=True):
    url = "https://www.google.com/search?q=" + query.replace(" ", "+")

    if debug:
        print("[BROWSER] Searching:", query)
        print("[BROWSER] URL:", url)

    webbrowser.open(url)

def new_tab(debug=True):
    if debug:
        print("[BROWSER] New tab")
    press_combo(["CTRL", "T"], debug=debug)

def close_tab(debug=True):
    if debug:
        print("[BROWSER] Close tab")
    press_combo(["CTRL", "W"], debug=debug)