# Auto-generated by scaffold.py
# os_actions/keyboard_utils.py
# Low-level keyboard injection
# ONLY module allowed to send key events

import ctypes
import time

SendInput = ctypes.windll.user32.SendInput

INPUT_KEYBOARD = 1
KEYEVENTF_KEYUP = 0x0002

# Virtual key codes (Windows)
VK = {
    "CTRL": 0x11,
    "SHIFT": 0x10,
    "ALT": 0x12,
    "ENTER": 0x0D,
    "TAB": 0x09,
    "ESC": 0x1B,
    "UP": 0x26,
    "DOWN": 0x28,
    "LEFT": 0x25,
    "RIGHT": 0x27
}

class KEYBDINPUT(ctypes.Structure):
    _fields_ = [
        ("wVk", ctypes.c_ushort),
        ("wScan", ctypes.c_ushort),
        ("dwFlags", ctypes.c_ulong),
        ("time", ctypes.c_ulong),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]

class INPUT(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_ulong),
        ("ki", KEYBDINPUT),
    ]

def _key_event(vk: int, down: bool, debug=True):
    flags = 0 if down else KEYEVENTF_KEYUP
    inp = INPUT(INPUT_KEYBOARD, KEYBDINPUT(vk, 0, flags, 0, None))
    SendInput(1, ctypes.byref(inp), ctypes.sizeof(inp))

    if debug:
        action = "DOWN" if down else "UP"
        print(f"[KEYBOARD] {action} vk={vk}")

def press_combo(keys: list, delay=0.05, debug=True):
    if debug:
        print("[KEYBOARD] Press combo:", keys)

    for k in keys:
        _key_event(VK[k], True, debug)

    time.sleep(delay)

    for k in reversed(keys):
        _key_event(VK[k], False, debug)

def type_text(text: str, delay=0.01, debug=True):
    if debug:
        print(f"[KEYBOARD] Typing text ({len(text)} chars)")

    for ch in text:
        vk = ord(ch.upper())
        ctypes.windll.user32.keybd_event(vk, 0, 0, 0)
        ctypes.windll.user32.keybd_event(vk, 0, KEYEVENTF_KEYUP, 0)
        time.sleep(delay)