# Auto-generated by scaffold.py
# os_actions/os_actions.py
# OS-level helpers (NO keyboard logic here)

import subprocess
import webbrowser

def open_website(url: str, debug=True):
    if debug:
        print("[OS] Opening website:", url)
    webbrowser.open(url)

def open_app(app_name: str, debug=True):
    if debug:
        print("[OS] Opening app:", app_name)

    try:
        subprocess.Popen(app_name, shell=True)
    except Exception as e:
        print("[OS ERROR] Failed to open app:", e)