# Auto-generated by scaffold.py
# brain/keyboard_brain.py
# Deterministic executor: intent -> actions

from brain.state import State
from os_actions.keyboard_utils import press_combo, type_text
from os_actions.os_actions import open_website, open_app
from brain.context import  is_browser_context
from utils.tts import speak

class KeyboardBrain:
    def __init__(self, state: State, settings: dict, keys: dict):
        self.state = state
        self.settings = settings
        self.keys = keys

        self.debug = settings["debug"]["print_execution"]

        if self.debug:
            print("[KEYBOARD BRAIN INIT]")
            print("[KEYBOARD BRAIN] Default mode:", self.state.mode)

    def execute(self, intent: dict):
        intent_id = intent["intent_id"]
        params = intent.get("params", {})

        if self.debug:
            print(f"[EXECUTE] intent_id={intent_id}, params={params}")

        # Track last intent
        self.state.set_last_intent(intent_id)

        # ---------- MODE SWITCH ----------
        if intent_id == "MODE_SWITCH":
            mode = params.get("mode")
            if mode:
                self.state.set_mode(mode)
            else:
                print("[EXECUTE ERROR] MODE_SWITCH missing mode")
            return

        # ---------- OPEN WEBSITE ----------
        if intent_id == "OPEN_WEBSITE":
            url = params.get("url")
            if url:
                open_website(url)
                self.state.set_active_app("browser")
            else:
                print("[EXECUTE ERROR] OPEN_WEBSITE missing url")
            return

        # ---------- OPEN APP ----------
        if intent_id == "OPEN_APP":
            app = params.get("app_name")
            if app:
                open_app(app)
                self.state.set_active_app(app)

                msg = f"Opening {app}"
                print(msg)
                speak(msg, debug=self.debug)
            else:
                print("[EXECUTE ERROR] OPEN_APP missing app_name")
            return

        # ---------- SEARCH WEB ----------
        if intent_id == "SEARCH_WEB":
            query = params.get("query")
            if intent_id == "SEARCH_WEB":
                query = params.get("query")
                if not query:
                    print("[EXECUTE ERROR] SEARCH_WEB missing query")
                    return

                search_url = "https://www.google.com/search?q=" + query.replace(" ", "+")

                if is_browser_context(self.state):
                    if self.debug:
                        print("[CONTEXT] Browser active → searching in browser")
                        msg = f"Searching for {query}"
                        print(msg)
                        speak(msg, debug=self.debug)
                    open_website(search_url)
                else:
                    if self.debug:
                        print("[CONTEXT] No browser active → opening browser")
                    open_website(search_url)
                    self.state.set_active_app("browser")

            return

        # ---------- TEXT INPUT ----------
        if intent_id == "TEXT_INPUT":
            content = params.get("content", "")
            if content:
                type_text(content)
            else:
                print("[EXECUTE WARNING] TEXT_INPUT empty content")
            return

        # ---------- CODE GENERATION ----------
        if intent_id == "CODE_GENERATION":
            code = params.get("code", "")
            if code:
                type_text(code)
            else:
                print("[EXECUTE WARNING] CODE_GENERATION empty code")
            return

        # ---------- KEY COMMAND ----------
        if intent_id == "KEY_COMMAND":
            keys = params.get("keys")
            if keys:
                press_combo(keys)
            else:
                print("[EXECUTE ERROR] KEY_COMMAND missing keys")
            return

        # ---------- NAVIGATION ----------
        if intent_id == "NAVIGATION":
            direction = params.get("direction", "").upper()
            count = params.get("count", 1)

            if direction in self.keys["virtual_keys"]:
                for i in range(count):
                    if self.debug:
                        print(f"[NAVIGATION] {direction} ({i+1}/{count})")
                    press_combo([direction])
            else:
                print("[EXECUTE ERROR] Invalid navigation direction:", direction)
            return

        # ---------- UNKNOWN ----------
        print(f"[EXECUTE] Intent not handled: {intent_id}")