# Auto-generated by scaffold.py
# brain/state.py
# Holds global execution state
# NO OS calls here

class State:
    def __init__(self, default_mode="COMMAND", debug=True):
        self.mode = default_mode
        self.active_app = None
        self.last_intent = None
        self.awaiting_param = None
        self.debug = debug

        if self.debug:
            print(f"[STATE INIT] mode={self.mode}")

    def set_mode(self, mode: str):
        if self.debug:
            print(f"[STATE] Mode change requested: {self.mode} -> {mode}")
        self.mode = mode

    def set_active_app(self, app_name: str):
        if self.debug:
            print(f"[STATE] Active app set to: {app_name}")
        self.active_app = app_name

    def set_last_intent(self, intent_id: str):
        if self.debug:
            print(f"[STATE] Last intent updated: {intent_id}")
        self.last_intent = intent_id

    def snapshot(self) -> dict:
        snap = {
            "mode": self.mode,
            "active_app": self.active_app,
            "last_intent": self.last_intent
        }
        if self.debug:
            print(f"[STATE SNAPSHOT] {snap}")
        return snap
    
    
    def set_awaiting(self, param: str):
        if self.debug:
            print(f"[STATE] Awaiting param: {param}")
        self.awaiting_param = param

    def clear_awaiting(self):
        if self.debug:
            print("[STATE] Cleared awaiting param")
        self.awaiting_param = None